repository: MajinBuuOnSecurity/MajinBuuOnSecurity.github.io

title: Majin Buu on Security
author: Majin Buu
avatar: /logo.jpeg
email: majinbuuonsec@gmail.com
skin: sunrise

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - vendor/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpeg
social:
  name: Majin Buu
  links:
    - https://github.com/MajinBuuOnSecurity
lang: en
